### ISSUE TITLE
Execute a form-based survey for first pass at an impact report

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#107]
### **Context:**

The results of the discovery work in #62 are:

1. We will invest in a sustainable, long-term solution for collecting impact data by building a survey app in the Django admin, targeted for the Nutmeg release

2. In the meantime, we will execute a form-based survey to inform a first pass at an impact report. The survey will serve the following purposes:

- Inform ongoing conversations about product strategy and serve as data points for the Board and ToC
- Serve as a reference point for the community
- Serve as a baseline of data, which we will build on and enhance over time with better data-gathering techniques
- Be presentable as a draft impact report for the April conference

### **Approach:**

Produce two methods for gathering survey data: 1) A manual FormAssembly doc for each Instance 2) a Google Sheet template for select multi-tenancy Instance providers

### **Tasks:**

- [ ] Edit/prune the current FormAssembly questions to make the survey process as quick and easy as possible
- [ ] Create technical documentation with suggested queries to be circulated with the FormAssembly survey
- [ ] Create a Google Sheet template and method for collecting data from multi-tenancy Instances
- [ ] Define methods and processes for communicating with all Service Providers 
- [ ] Send the survey with clear due dates
- [ ] Collect and analyze the data, including integrating it with the Heroku reports (https://github.com/openedx/openedx-census/issues/9)

**Comment by jmakowski1123** [comment]
@ormsbee and @e0d  Would love your thoughts based on your work and input into #62 . Have I captured all relevant next step tasks here? If yes, I'll convert them to Issues. Feel free to add!

**Comment by e0d** [comment]
This looks right to me.

**Comment by sarina** [comment]
All tasks are marked done - can this ticket be closed?
