### ISSUE TITLE
Ensure all in-flight work across ecosystem is represented on the Community Roadmap

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#193]
### **Context**

There is collective consensus across the community, tCRIL and 2U that a public, community roadmap for Open edX makes sense and fills a critical space in Open edX workflows. The target goals (as identified in the draft Product Working Group proposal) of the Community Roadmap are:

1. To comprehensively document all current work in-flight across the Open edX ecosystem.

2. To provide insight into early stage projects that may not be planned but are in the pipeline and may impact the Open edX ecosystem in significant ways.

3. To generate, document and prioritize ideas for future development and investment.

Getting to a Roadmap that effectively and comprehensively covers all three areas, as well as defining supporting workflows, is a large, multi-month project. The logical first Milestone is to focus on capturing and documenting current, in-flight work. This ticket is an epic to track tasks and progress toward this Milestone. 

### **Scope**

Currently, the draft Roadmap is largely comprised of a backlog (some of which may be outdated) of early stage ideas, many of them compiled during a 2020 product brainstorming session. There are also ad hoc tickets for some current blended development milestones, but not comprehensive coverage. Key missing pieces include: 1) Tickets representing current work from Providers across the ecosystem; 2) Current 2U work, particularly solo (not BD) work; 3) Current tCRIL work that intersects the platform. Representing current work from these 3 areas will ensure comprehensive coverage of all current work across the ecosystem. 

Additionally, there are underlying workflows that require definition for ongoing, sustainable maintenance. These include: 1) Workflow and documentation for Providers to add in-flight work, including baseline required data and information on tickets; 2) Workflow and cadence for updating work progress.

### **Success metrics**

Ideally, an up-to-date Roadmap that covers all current, in-flight work should be able to answer:

- What features or updates can we expect in the next Named Release?
- Where (what areas of the platform and/or user experience) are currently being invested in?
- Has work on Issue Y been completed?
- What was the scope and approach taken to Issue Z? 

In order to measure success on this Milestone, we could use the following questions as barometers:

- In the 2 weeks leading up to the June Nutmeg Release, how many "surprise" projects, tickets, PRs pop up?
- In the 2 weeks following the June Nutmeg Release, how many "surprise" projects, tickets, PRs pop up?
- Where do these originate from and how to make the process better for Olive?

### **Child tasks**

- [x] #194
- [x] #195
- [x] #209
- [x] #247
- [x] 1:1 support to all preferred providers to get work represented
- [x] Transfer relevant tCRIL epics
- [x] Implement 2U-tCRIL Product Sync meetings weekly
- [ ] Triangulate with all WGs to get their Boards represented
- [ ] Draft Best Practices Recommendations doc for upkeep cadence and practices
- [ ] Work with community to align Nutmeg release notes process with roadmap and identify gaps

**Comment by jmakowski1123** [comment]
The three remaining tasks have been transferred to the Product Working group and are being tracked in that project board. Closing this ticket in favor of shifting to the Product WG board to track and evolve the roadmap going forward.
