### ISSUE TITLE
Incorporate 2U developers into CC program

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#32]
### Scoping Access

- [ ] Phase 1: One team pilot (Q2 2022) - goals: work out the kinks, come up with framework and rules, define how teams will be represented in GH groups, figure out team vs team lead vs manager access need definitions
- [ ] Phase 2: Expand to 4-6 teams (Q3 2022)  - goals: test framework & rules from pilot, adjust as needed
- [ ] Phase 3: Expand to full team (late Q3 2022)

### Core Contributors

- [ ] Discovery work begins during latter part of the second phase as defined above.

## Description

[A writeup proposal of what changes to the program should be made is here.](https://docs.google.com/document/d/1qd27lxj8JugubOxhezxbNSgj84I5con3bfdDj1wuZZQ/edit#)

Please leave comments in the Google doc. At this time, the doc is going to remain private between 2U/edX and tCRIL.

**Comment by jmakowski1123** [comment]
#32, #10, #39 related to Ownership Proposal (in progress, cc @e0d )

**Comment by sarina** [comment]
Update: finished proposal and sent over to 2U for comment. Putting in "blocked" until they come back with a response.

**Comment by kdmccormick** [comment]
@sarina Something I was thinking about the other day: Manually managing CC permissions seems to be working well with the current size of the program. It could get tough, though, if we added the entirety of 2U OCM to the program while using that system. We may want to tackle https://github.com/openedx/terraform-github/issues/29 before pursing this issue.

Ofc, you've been administering the program, so you have a better perspective on this than I do.

**Comment by sarina** [comment]
@kdmccormick heh just seeing this... yeah as we discussed in grooming today, that is an upcoming priority

**Comment by sarina** [comment]
This is a very long running ticket that will have lots of stories/subtasks. A very rough granularity TO DO list is defined in the description of this ticket. I am going to put this on the epic board (to track the effort), and track the subtasks I'm tackling in my sprint ticket each sprint.

fyi @jmakowski1123

**Comment by sarina** [comment]
Closing this. This is more complicate than can be handled in one ticket. We've discussed strategies but ultimately 2U will have to drive this to an extent, because (per agreement terms) we cannot _make_ 2U become CCs (at least, with my definition that to be a CC, you can't be in push-pull-all; I believe that's not a unanimous take per talking with Xavier). I think this requires more groundwork conversations, then creating actionable tickets.
