### ISSUE TITLE
Developer Onboarding

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#41]
Developer onboarding is a perennial problem that we need to solve. It can be addressed in the context of the new Documentation schema. We should have content aimed at a specific persona: "Developer new to Open edX who needs to be oriented and onboarded".

With the framing, we could start by building a persona profile that identifies the key painpoints and challenges they run into when trying to become acquainted with the Open edX platform and how they might participate. Using that as a starting point, we can then identify which content is required in each of the four quadrants - how tos, quick start, reference and concepts.

Acceptance Criteria:

By the end of the project, we would have two documents in production: one quickstart guide for new developers, and one concept doc for new developers.

As such, milestones in this epic are:

- [x] Mapping/whiteboarding exercise to create an outline for each doc
- [x] Parse through all current documentation (readthedocs, wiki/confluence, repos) to find docs that currently exist that can be reused/edited
- [x] Writing/coding to fill gaps
- [x] Push through PR process

Related tasks:
- [x] https://github.com/openedx/tcril-engineering/issues/14
- [ ] https://github.com/openedx/tcril-engineering/issues/61

Original notes - Jan 5
Things we should have include:

- Robust platform documentation
- How-to onboard to coding documentation (devstack/Tutor docs)
- How to onboard to contributing code
- How to onboard to other types of contributions
- How to onboard as a Core Contributor
- How to onboard as a new tCRIL employee https://github.com/openedx/tcril-engineering/issues/9

These may be documents, onboarding courses hosted by the new tCRIL instance, or a mix of both.

cc @feanil @Carlos-Muniz

**Comment by jmakowski1123** [comment]
Two related items: #61 and #14

Epic needs subtask grooming and clarifying on Documentation Initiative #49

**Comment by jmakowski1123** [comment]
To be informed by #103

**Comment by sarina** [comment]
@jmakowski1123 feel free to edit the description of issues, too, to add info. That's a great one to have in the description! (also I'll add some text so people don't have to click through to the issue to understand what it is).

**Comment by jmakowski1123** [comment]
Notes from Planning 3/21 - Pull this ticket into Documentation discussion and refine relative to #60 and the next Milestones

**Comment by feanil** [comment]
@hurtstotouchfire no those have not been fleshed out yet, happy to take any suggestions you might have for them but hopefully we'll be focusing on that more post conference.

**Comment by feanil** [comment]
This now exists: https://docs.openedx.org/en/latest/developers/quickstarts/setup_a_backend_dev_environment.html
