### ISSUE TITLE
Find out which MFEs should be in Olive

### ISSUE THREAD

**Issue by arbrandes** [openedx/tcril-engineering#494]
Investigate which MFEs should be included in Olive, from a product perspective with a technical feasibility in mind.

The BTR is tracking this question here:

- [x] https://github.com/openedx/build-test-release-wg/issues/200
- [ ] #495

**Comment by arbrandes** [comment]
Looks like [we want authn](https://github.com/openedx/build-test-release-wg/issues/200#issuecomment-1292530590), too.  So as of now, the list to aim for is:

* frontend-app-course-authoring
* frontend-app-ora-grading
* frontend-app-learner-record
* frontend-app-authn

**Comment by arbrandes** [comment]
#### frontend-app-course-authoring

- [x] Minimal documentation: not present.  The README needs work.  Made [a PR](https://github.com/openedx/frontend-app-course-authoring/pull/381) to fix this, though.
- [x] Production readiness: In production at 2U.
- [x] i18n: Matches currently supported MFEs.
- [x] l10n: Matches currently supported MFEs.
- [x] a11y: Uses paragon extensively.
- [ ] Customizable header: not yet, but no learning-facing pages are exposed.  Likely not a concern.
- [x] Customizable footer: uses frontend-component-footer.
- [x] Branding module: imports brand-openedx and uses paragon variables
- [x] Branding friendly: no in-line explicit styles were found
- [ ] tutor-mfe plugin: none yet
- [ ] [Runtime configuration](https://github.com/openedx/frontend-wg/issues/103): not implemented
- [x] Deprecation: no legacy feature that this replaces is being removed in this release

Other considerations:

The new XBlock editors feature depends (heavily) on a component that lives in the edx org (https://github.com/edx/frontend-lib-content-components/).  Reportedly, however, the intention is to move it to openedx as capacity allows.

**Comment by arbrandes** [comment]
#### frontend-app-discussions

- [ ] Minimal documentation: not present.  The README needs work.
- [ ] Production readiness: not in production anywhere.
- [x] i18n: Better than most currently supported MFEs.
- [x] l10n: Matches currently supported MFEs.
- [x] a11y: Uses paragon extensively.
- [x] Customizable header: uses frontend-component-header.
- [x] Customizable footer: uses frontend-component-footer.
- [x] Branding module: imports brand-openedx and uses paragon variables
- [ ] Branding friendly: no in-line explicit styles were found, but there are hard-coded overrides in `index.scss`
- [ ] tutor-mfe plugin: none yet
- [ ] [Runtime configuration](https://github.com/openedx/frontend-wg/issues/103): not implemented
- [x] Deprecation: no legacy feature that this replaces is being removed in this release
- [ ] Dependencies: It depends on [frontend-app-course-authoring](https://github.com/openedx/frontend-app-course-authoring/) for configuration, and it is not not included in Tutor at this time.

Other considerations:

It is reported that several bugs were found in production at 2U, and thus the MFE was pulled until they were fixed.  The target date for said fixes was set to "early November".

**Comment by arbrandes** [comment]
#### frontend-app-ora-grading

- [x] Minimal documentation: present.  (There's even [a manual](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/open_response_assessments/ORA_Staff_Grading.html#ora-staff-grading).)
- [x] Production readiness: in production at 2U.
- [x] i18n: Matches currently supported MFEs.
- [x] l10n: Matches currently supported MFEs.
- [x] a11y: Uses paragon extensively.
- [x] Customizable header: uses frontend-component-header.
- [x] Customizable footer: uses frontend-component-footer.
- [x] Branding module: imports brand-openedx and uses paragon variables
- [x] Branding friendly: no in-line explicit styles were found
- [ ] tutor-mfe plugin: none yet
- [ ] [Runtime configuration](https://github.com/openedx/frontend-wg/issues/103): not implemented
- [x] Deprecation: no legacy feature that this replaces is being removed in this release
- [x] Dependencies: no external ones.

**Comment by arbrandes** [comment]
#### frontend-app-learner-record

- [x] Minimal documentation: present.
- [x] Production readiness: in production at 2U.
- [x] i18n: Matches currently supported MFEs.
- [ ] l10n: Only localized into Spanish.
- [x] a11y: Uses paragon extensively.
- [x] Customizable header: uses frontend-component-header.
- [x] Customizable footer: uses frontend-component-footer.
- [x] Branding module: imports brand-openedx and uses paragon variables
- [x] Branding friendly: no in-line explicit styles were found
- [x] tutor-mfe plugin: not merged yet, but [there's a PR](https://github.com/overhangio/tutor-mfe/pull/63).
- [ ] [Runtime configuration](https://github.com/openedx/frontend-wg/issues/103): not implemented.
- [x] Deprecation: no legacy feature that this replaces is being removed in this release
- [ ] Dependencies: [credentials](https://github.com/openedx/credentials), not currently a part of Tutor.  There's [a credentials plugin](https://discuss.overhang.io/t/introducing-the-credentials-plugin/2809), but at this time it's not clear how well maintained and up to date it is, including if it will be upgrade for Olive.

**Comment by arbrandes** [comment]
#### frontend-app-authn

- [ ] Minimal documentation: not present.
- [x] Production readiness: reportedly in production at 2U.
- [x] i18n: Matches currently supported MFEs.
- [x] l10n: Matches currently supported MFEs.
- [x] a11y: Uses paragon extensively.
- N/A: Customizable header: doesn't have a header
- N/A: Customizable footer: doesn't have a footer
- [x] Branding module: imports brand-openedx and uses paragon variables
- [ ] Branding friendly: uses in-line styles such as `large-yellow-line`
- [ ] tutor-mfe plugin: none yet
- [x] [Runtime configuration](https://github.com/openedx/frontend-wg/issues/103): not merged yet, but there's [a PR](https://github.com/openedx/frontend-app-authn/pull/654).
- [x] Deprecation: no legacy feature that this replaces is being removed in this release
- [x] Dependencies: no external ones.

**Comment by arbrandes** [comment]
The above findings were documented as a matrix here:

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3571056752/Olive+MFE+Candidate+Requirements+Matrix

What's missing now is a decision by BTR on how to proceed, as none of them passed the bar fully.  Hopefully we'll have one by tomorrow.

**Comment by arbrandes** [comment]
See https://github.com/openedx/build-test-release-wg/issues/200#issuecomment-1307312733 for the conclusion.
