### ISSUE TITLE
Roll out GitHub issues Phase 1: DEPR for smaller repos

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#74]
Follow on to https://github.com/openedx/tcril-engineering/issues/10

We need to:

- [x] Create default templates for repo issues (test on one repo)
- [x] Socialize and get consensus on what the templates look like (communicate to all stakeholders what we're doing and why (how we're mitigating spam, evidence from smaller repos that spam is not a problem, what it looks like to open an issue and how we're redirecting to the forums as needed, whose responsibility it is to monitor new issues and at what frequency, when it's ok to close an issue))
- [x] Get workflow automation running to dump new DEPRs onto the appropriate board
- [x] Implement Phase 1
- [x] Monitor Phase 1 and create additional phases based on results

## Phase 1

- [x] implement default DEPR template & workflow globally in .github
- [x] move workflow into either all repos, or just repos that currently have open depr tickets
- [x] for repos that currently have issues off, move issue template overrides into repo & turn issues on

We should consider:

* A core contributor role (proj or prod mgr, I think) for assisting with monitoring created issues and redirecting them
* Creating an easy to see view across (ideally) all repos to serve as a triage board

Places where conversation has happened:

* https://discuss.openedx.org/t/new-blip-on-tech-radar-github-issues-provisional/6508
* https://openedx.slack.com/archives/C02M89BSV9A/p1642693537008400
* https://openedx.slack.com/archives/C1L370YTZ/p1642017087000400 (announcement of the change, no comments)
* Some 1-1 convos I am not very aware of

**Comment by sarina** [comment]
RE Checkbox 1:

Any thoughts on how this look/ how it might address concerns around opening up GitHub issues on more repos? https://github.com/openedx/tcril-onboarding/issues/new/choose

This is the most locked-down version we can make. Making blank issues is disabled (unlike on tcril-engineering). You’re clearly directed to the forums. And the DEPR template’s first line says “this is only for DEPR”. I could make that line more explicit about going to the forums; I could even make a checkbox to make people ack that they understand the purpose of the ticket, but I feel that’s overkill unless we actually see that there’s a problem.
