### ISSUE TITLE
Develop End-to-end Information Strategy

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#89]
6/9 - There is enough overlap between this ticket and the documentation initiative that I think we can call it closed.

In order to develop a complete Documentation/Information strategy, we should be able to answer these questions:

Part I:
First is the “what and why” - What documents do we need? Which breaks down into - Who are the documents for and what problems do they solve?

Answers to these questions will inform strategy execution:

Part II:
Second is the “where and how” - Where should those documents live and how should they be organized?
Also - what documents are missing? Need to be updated? 

I suggest that we focus on the Part I set of questions first. The answers to the first set of questions would drive and inform the approach to Part II. 

Part I Milestones:

- [x] https://github.com/openedx/tcril-engineering/issues/103

- [x] https://github.com/openedx/tcril-engineering/issues/104

Part II: Milestones:

- [x] https://github.com/openedx/tcril-engineering/issues/60

-----
Context/Background info

Currently we have information/documentation in

- Repos
- Read The Docs
- The Wiki
- The Open edX Website

We should:

- have a clear POV of the jobs that each of these resources do
- document that so it's clear and understood
- ensure that all of our information and documentation is complementary
- generally reduce confusion about where to put things, find things

**Comment by jmakowski1123** [comment]
This reads to me like an Initiative umbrella, with a number of existing tickets at epic and task level. Shifting this to groom so we can scope it as a holistic project with a view of all related documentation tickets:

https://github.com/openedx/tcril-engineering/issues/49
https://github.com/openedx/tcril-engineering/issues/41
https://github.com/openedx/tcril-engineering/issues/60
https://github.com/openedx/tcril-engineering/issues/35

**Comment by robrap** [comment]
Here is a related link to all tCRIL Roadmap issues with a roadmap alignment of "documentation": https://github.com/orgs/openedx/projects/12/views/1?filterQuery=tcril-roadmap-alignment%3Adocumentation+
